/*
* Programmed By: Aaron Gabrielle Dichoso 
*
* Description:
* 	LRRHFunctions_prototype.h: Contains the function prototypes of LRRHFunctions.c
* Last Modified: 28/01/2022
*/

#include <limits.h>

int     convertDirectionSymbolToXMovement       (char cCurrentDirection);
int     convertDirectionSymbolToYMovement       (char cCurrentDirection);
char    getOppositeDirection                    (char cDirection);
char    directionVectorToSymbol                 (int xMovement, 
                                                int yMovement);
int     computeWoodsmanDistance                 (char * pPlayGrid, 
                                                int nGridSize);
char    forwardLRRH                             (int * pNumOfMovements, 
                                                int * pLRRHXLocation, 
                                                int * pLRRHYLocation, 
                                                char * pLRRHTile, 
                                                char * pCurrentDirection, 
                                                int nGridSize, 
                                                char cPreviousTileSymbol);
char    simulateRightLRRHRotation               (char cTestDirection);
char    simulateLeftLRRHRotation                (char cTestDirection);
void    smartRotateLRRH                         (int * pNumOfSenses, 
                                                int * pNumOfRotations, 
                                                int * pNumOfMovements,
                                                int * pNumOfTurns, 
                                                char * pCurrentDirection, 
                                                char cNewDirection,
                                                char * pLRRHTile, 
                                                char * pPlayGrid, 
                                                int nGridSize, 
                                                int nStepByStepMode, 
                                                int nHasSounds);
void    rotateRightLRRH                         (int * pNumOfRotations, 
                                                char * pCurrentDirection, 
                                                char * pLRRHTile);
void    rotateLeftLRRH                          (int * pNumOfRotations, 
                                                char * pCurrentDirection, 
                                                char * pLRRHTile);
char    senseLRRH                               (int * pNumOfSenses, 
                                                int * pLRRHXLocation, 
                                                int * pLRRHYLocation,
                                                char * pLRRHTile, 
                                                char * pCurrentDirection, 
                                                int nGridSize);
void    senseAndQueueLRRHAdjacentTiles          (int * pLRRHXLocation, 
                                                int * pLRRHYLocation,
                                                int * pWolfXCoord, 
                                                int * pWolfYCoord,
                                                int * pSensedTiles, 
                                                char * pPlayGrid, 
                                                char * pLRRHViewDirection, 
                                                int nGridSize,
                                                int * pNumOfSenses, 
                                                int * pNumOfRotations, 
                                                int * pNumOfMovements, 
                                                int * pNumOfTurns,
                                                int * pIsGrannyApproachable, 
                                                int * pHasBread, 
                                                int * pHasSensedBread,  
                                                int * pHasSensedFlower, 
                                                int * pHasSensedWoodsman, 
                                                int * pHasSensedGrandma,
                                                Queue * pXGridQueue, 
                                                Queue * pYGridQueue, 
                                                int nStepByStepMode, 
                                                int nHasSounds);
void    senseAndQueueLRRHForwardTile            (int * pLRRHXLocation, 
                                                int * pLRRHYLocation,
                                                int * pWolfXCoord, 
                                                int * pWolfYCoord,
                                                int * pSensedTiles, 
                                                char * pPlayGrid, 
                                                char * pLRRHViewDirection, 
                                                int nGridSize,
                                                int * pNumOfSenses, 
                                                int * pNumOfRotations, 
                                                int * pNumOfMovements, 
                                                int * pNumOfTurns,
                                                int * pIsGrannyApproachable, 
                                                int * pHasBread, 
                                                int * pHasSensedBread, 
                                                int * pHasSensedFlower, 
                                                int * pHasSensedWoodsman, 
                                                int * pHasSensedGrandma,
                                                Queue * pXGridQueue, 
                                                Queue * pYGridQueue, 
                                                int nStepByStepMode, 
                                                int nHasSounds, 
                                                char cDirectionSymbol);
void    generateAStarPath                       (int nLRRHXLocation, 
                                                int nLRRHYLocation,
                                                int nNewLRRHXLocation, 
                                                int nNewLRRHYLocation,
                                                int * pSensedTiles, 
                                                char * pPlayGrid,
                                                int nGridSize, 
                                                Queue * pActionQueue, 
                                                int * pIsDestinationValid);
void    generatePathToClosestBakery             (int nLRRHXLocation, 
                                                int nLRRHYLocation, 
                                                int * nBakeryXCoord, 
                                                int * nBakeryYCoord,
                                                int * pHasSensedBread, 
                                                int * pSensedTiles, 
                                                char * pPlayGrid,
                                                int nGridSize, 
                                                Queue * pActionQueue, 
                                                int * pIsDestinationValid);
void    moveLRRHToPath                          (int * pLRRHXLocation, 
                                                int * pLRRHYLocation,
                                                int nNewLRRHXLocation, 
                                                int nNewLRRHYLocation,
                                                int * pWolfXCoord, 
                                                int * pWolfYCoord,
                                                Queue * pActionQueue, 
                                                int * pNumOfSenses, 
                                                int * pNumOfRotations, 
                                                int * pNumOfMovements, 
                                                int * pNumOfTurns, 
                                                int nGridSize, 
                                                char * pPlayGrid, 
                                                int * pWalkedTiles, 
                                                int * pSensedTiles,
                                                int * pHasFlower, 
                                                int * pHasBread, 
                                                int * pVisitedWoodsman, 
                                                int * pWasBreadTaken,
                                                char * pLRRHViewDirection, 
                                                char * pMovementScenario, 
                                                int nStepByStepMode, 
                                                int nHasSounds);
void    moveLRRHToPathWhileSensing              (int * pLRRHXLocation, 
                                                int * pLRRHYLocation,
                                                int nNewLRRHXLocation, 
                                                int nNewLRRHYLocation,
                                                int * pWolfXCoord, 
                                                int * pWolfYCoord,
                                                Queue * pActionQueue, 
                                                Queue * pXGridQueue, 
                                                Queue * pYGridQueue,
                                                int * pNumOfSenses, 
                                                int * pNumOfRotations, 
                                                int * pNumOfMovements, 
                                                int * pNumOfTurns, 
                                                int nGridSize, 
                                                char * pPlayGrid, 
                                                int * pWalkedTiles, 
                                                int * pSensedTiles,
                                                int * pHasFlower, 
                                                int * pHasBread, 
                                                int * pVisitedWoodsman,
                                                int * pWasBreadTaken,
                                                int * pHasSensedBread, 
                                                int * pHasSensedFlower, 
                                                int * pHasSensedWoodsman, 
                                                int * pHasSensedGrandma, 
                                                int * pIsGrannyApproachable,
                                                char * pLRRHViewDirection, 
                                                char * pMovementScenario, 
                                                int nStepByStepMode, 
                                                int nHasSounds);
void    waitForNextTurn                         (int * pNumOfTurns, 
                                                int nStepByStepMode, 
                                                int nHasSounds);
int     sensedEveryTile                         (int * pSensedTiles,
                                                int nGridSize);
void    recallSensedTile                        (int nSenseValue, 
                                                int * pXCoord, 
                                                int * pYCoord, 
                                                int * pSensedTiles, 
                                                int nGridSize);
int     isWolfTileSkippable                     (int nLRRHXLocation, 
                                                int nLRRHYLocation, 
                                                int nXGridLocation, 
                                                int nYGridLocation, 
                                                int * pSensedTiles, 
                                                int nGridSize,
                                                int nQueueCapacity);